export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_LOADING = "SET_LOADING ";
export const SET_PRODUCTS_FAIL = "SET_PRODUCTS_FAIL"

export const SET_PRODUCT = "SET_PRODUCT";
export const SET_PRODUCT_FAIL = "SET_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST='DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS='DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL='DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET='DELETE_PRODUCT_RESET';

export const CREATE_PRODUCT_REQUEST='CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS='CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL='CREATE_PRODUCT_FAIL';
export const CREATE_PRODUCT_RESET='CREATE_PRODUCT_RESET';

export const UPDATE_PRODUCT_REQUEST='UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL='UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET='UPDATE_PRODUCT_RESET';
//action for cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const RESET_CART_ITEM ="RESET_CART_ITEM";

//action for login
export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST';
export const SET_AUTH='SET_AUTH';
export const SET_ERROR='SET_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';


export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';

export const SET_PROFILE = 'SET_PROFILE';
export const RESET_PROFILE = 'RESET_PROFILE'; 
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_PROFILE_ERROR ='SET_PROFILE_ERROR';

export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';
export const SET_PAYMENT_METHOD='SET_PAYMENT_METHOD';

//for order
export const SET_ORDER_REQUEST = 'SET_ORDER_REQUEST';
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
export const SET_ORDER_FAIL = 'SET_ORDER_FAIL';
export const RESET_ORDER_SUCCESS ='RESET_ORDER_SUCCESS';

export const GET_ORDER_REQUEST ='GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS='GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL'

export const SET_PAY_REQUEST = 'SET_PAY_REQUEST';
export const SET_PAY_SUCCESS = 'SET_PAY_SUCCESS';
export const SET_PAY_FAIL = 'SET_PAY_FAIL';
export const ORDER_PAY_RESET ='ORDER_PAY_RESET';

export const GET_MY_ORDER_REQUEST = 'GET_MY_ORDER_REQUEST';
export const GET_MY_ORDER_SUCCESS = 'GET_MY_ORDER_SUCCESS';
export const GET_MY_ORDER_FAIL = 'GET_MY_ORDER_FAIL';
export const RESET_ORDER ='RESET_ORDER';

export const GET_ORDERS_REQUEST='GET_PRODUCT_REQUEST';
export const GET_ORDERS_SUCCESS='GET_PRODUCT_SUCCESS';
export const GET_ORDERS_FAIL='GET_PRODUCT_FAIL';

export const ORDER_DELIVER_REQUEST='ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS='ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL='ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET='ORDER_DELIVER_RESET';

export const USER_LIST_REQUEST ="USER_LIST_REQUEST";
export const USER_LIST_SUCCESS ="USER_LIST_SUCCESS";
export const USER_LIST_FAIL ="USER_LIST_FAIL"
export const USER_LIST_RESET ="USER_LIST_RESET"

export const USER_DELETE_REQUEST="USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL ="USER_DELETE_FAIL";

export const GET_USER_REQUEST ="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAIL ="GET_USER_FAIL";

export const PUT_USER_REQUEST ="PUT_USER_REQUEST";
export const PUT_USER_SUCCESS="PUT_USER_SUCCESS";
export const PUT_USER_FAIL ="PUT_USER_FAIL";
export const PUT_USER_RESET="PUT_USER_RESET";


export const RESET_ORDER_DETAIL='REST_ORDER_DETAIL';


export const  PRODUCT_REVIEW_REQUEST ='PRODUCT_REVIEW_REQUEST';
export const  PRODUCT_REVIEW_SUCCESS ='PRODUCT_REVIEW_SUCCESS';
export const  PRODUCT_REVIEW_FAIL ='PRODUCT_REVIEW_FAIL';
export const  PRODUCT_REVIEW_RESET ='PRODUCT_REVIEW_RESET';